### ISSUE TITLE
Handlebars not supporting styleModifier

### ISSUE THREAD

**Issue by udg-sabrina-nebauer** [pattern-lab/patternengine-node-handlebars#11]
I am using Pattern Lab Node `v1.2.0` on `Mac`, using the `grunt` configuration.

##### Expected Behavior
Including atoms like {{> atoms/form-items/label-field:visuallyhidden }} should work like described here: http://patternlab.io/docs/pattern-stylemodifier.html

##### Actual Behavior
When running patternlab via grunt, I'm getting "Warning: The partial atoms/form-items/label-field:visuallyhidden could not be found Use --force to continue." and building stops. Atom is not included in file.

**Comment by bmuenzenmeyer** [comment]
Per the readme,  handlebars had a better way of doing this.  https://github.com/pattern-lab/patternengine-node-handlebars
