### ISSUE TITLE
Default include syntax not working 

### ISSUE THREAD

**Issue by gergan** [pattern-lab/patternengine-node-handlebars#8]
I am using Pattern Lab Node `v1.0.2` on `Windows`, using the `gulp` configuration.

##### Expected Behavior
The verbose syntax (or as the documentation is referring to it - default include syntax) for the partials is functioning as documented http://patternlab.io/docs/pattern-including.html#the-default-include-syntax

##### Actual Behavior
The default include syntax does not work and it is documented in a comment, which is not entirely correct:

`// register verbose syntax? No, it seems that Handlebars can't tolerate`
`// slashes in partial names.`

The problem, which is described there, originates from patternlab-node's erroneous definition for the verbosePartial property (which most probably is incorrectly defined as problem with the subdir property in https://github.com/pattern-lab/patternlab-node/issues/559)

##### Steps to Reproduce
Use Handelbar Templates with default include syntax in your patternlab.

**Comment by bmuenzenmeyer** [comment]
https://www.npmjs.com/package/patternengine-node-handlebars
